[package]
name = "webmine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.219"
serde_derive = "1.0.219"
serde_yaml = "0.9.34"
tokio = { version = "1.44.2", features = ["full"]}
